"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


"""

"""
*****first*****
sum1=0
a=1
b=2
while a<4000000:
    a,b=b,a+b
    if (a%2==0):
        sum1+=a
print(sum1)

"""

sum1=0
a,b=1,2
while (True):
    a,b=b,a+b
    if (a>4000000):
        break
    elif (a%2==0):
        sum1+=a
print(sum1)
